### ISSUE TITLE
Use single character for rendered log severity

### ISSUE THREAD

**Issue by caspiano** [place-labs/log-backend#7]
**Is your feature request related to a problem? Please describe.**

The weird alignment of log levels via spacing makes logs look aesthetically out of whack.

**Describe the solution you'd like**

Use a single character as the log levels all start with unique characters.
This will have the added benefit of aligning the log statement

**Comment by jeremyw24** [comment]
Ensure logs are searchable i.e. [E] [W] [D] [I] [T]

**Comment by caspiano** [comment]
Closed by spider-gazelle/action-controller/pull/46
